// <auto-generated>
//     This code was generated from Strings.resx.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated with ResXFileCodeGenerator.
// </auto-generated>

namespace OfficeMetaCleaner.Core;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings
{
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeMetaCleaner.Core.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    internal static string Core_FileNotFound
    {
        get
        {
            return ResourceManager.GetString("Core_FileNotFound", resourceCulture);
        }
    }

    internal static string Core_UnknownContainer
    {
        get
        {
            return ResourceManager.GetString("Core_UnknownContainer", resourceCulture);
        }
    }

    internal static string Core_InPlaceWarning
    {
        get
        {
            return ResourceManager.GetString("Core_InPlaceWarning", resourceCulture);
        }
    }

    internal static string Core_DropPartDetail
    {
        get
        {
            return ResourceManager.GetString("Core_DropPartDetail", resourceCulture);
        }
    }

    internal static string Core_StripImageDetail
    {
        get
        {
            return ResourceManager.GetString("Core_StripImageDetail", resourceCulture);
        }
    }

    internal static string Core_WriteFailed
    {
        get
        {
            return ResourceManager.GetString("Core_WriteFailed", resourceCulture);
        }
    }

    internal static string Core_PartFailed
    {
        get
        {
            return ResourceManager.GetString("Core_PartFailed", resourceCulture);
        }
    }

    internal static string Core_ScrubXmlDetail
    {
        get
        {
            return ResourceManager.GetString("Core_ScrubXmlDetail", resourceCulture);
        }
    }

    internal static string Core_ContentTypesDetail
    {
        get
        {
            return ResourceManager.GetString("Core_ContentTypesDetail", resourceCulture);
        }
    }

    internal static string Core_RelsDetail
    {
        get
        {
            return ResourceManager.GetString("Core_RelsDetail", resourceCulture);
        }
    }

    internal static string Core_PrivacyFlagDetail
    {
        get
        {
            return ResourceManager.GetString("Core_PrivacyFlagDetail", resourceCulture);
        }
    }

    internal static string Core_CfbWouldClear
    {
        get
        {
            return ResourceManager.GetString("Core_CfbWouldClear", resourceCulture);
        }
    }

    internal static string Core_CfbStreamMissing
    {
        get
        {
            return ResourceManager.GetString("Core_CfbStreamMissing", resourceCulture);
        }
    }

    internal static string Core_CfbStreamSkipped
    {
        get
        {
            return ResourceManager.GetString("Core_CfbStreamSkipped", resourceCulture);
        }
    }

    internal static string Core_CfbError
    {
        get
        {
            return ResourceManager.GetString("Core_CfbError", resourceCulture);
        }
    }

    internal static string Core_CfbCleared
    {
        get
        {
            return ResourceManager.GetString("Core_CfbCleared", resourceCulture);
        }
    }

    internal static string Core_AceWindowsOnly
    {
        get
        {
            return ResourceManager.GetString("Core_AceWindowsOnly", resourceCulture);
        }
    }

    internal static string Core_AceNoDriver
    {
        get
        {
            return ResourceManager.GetString("Core_AceNoDriver", resourceCulture);
        }
    }

    internal static string Core_AceLaunchFailed
    {
        get
        {
            return ResourceManager.GetString("Core_AceLaunchFailed", resourceCulture);
        }
    }

    internal static string Core_AceNoEngine
    {
        get
        {
            return ResourceManager.GetString("Core_AceNoEngine", resourceCulture);
        }
    }

    internal static string Core_AceError
    {
        get
        {
            return ResourceManager.GetString("Core_AceError", resourceCulture);
        }
    }

    internal static string Core_AceWouldDelete
    {
        get
        {
            return ResourceManager.GetString("Core_AceWouldDelete", resourceCulture);
        }
    }

    internal static string Core_AceDeleted
    {
        get
        {
            return ResourceManager.GetString("Core_AceDeleted", resourceCulture);
        }
    }

    internal static string Core_AceDeleteFailed
    {
        get
        {
            return ResourceManager.GetString("Core_AceDeleteFailed", resourceCulture);
        }
    }

    internal static string Core_NothingFound
    {
        get
        {
            return ResourceManager.GetString("Core_NothingFound", resourceCulture);
        }
    }

    internal static string Cli_UnknownCommand
    {
        get
        {
            return ResourceManager.GetString("Cli_UnknownCommand", resourceCulture);
        }
    }

    internal static string Cli_OutNeedsValue
    {
        get
        {
            return ResourceManager.GetString("Cli_OutNeedsValue", resourceCulture);
        }
    }

    internal static string Cli_NoInput
    {
        get
        {
            return ResourceManager.GetString("Cli_NoInput", resourceCulture);
        }
    }

    internal static string Cli_InPlaceOutConflict
    {
        get
        {
            return ResourceManager.GetString("Cli_InPlaceOutConflict", resourceCulture);
        }
    }

    internal static string Cli_InvalidLang
    {
        get
        {
            return ResourceManager.GetString("Cli_InvalidLang", resourceCulture);
        }
    }

    internal static string Cli_NoFiles
    {
        get
        {
            return ResourceManager.GetString("Cli_NoFiles", resourceCulture);
        }
    }

    internal static string Cli_FoundFiles
    {
        get
        {
            return ResourceManager.GetString("Cli_FoundFiles", resourceCulture);
        }
    }

    internal static string Cli_BusyFiles
    {
        get
        {
            return ResourceManager.GetString("Cli_BusyFiles", resourceCulture);
        }
    }

    internal static string Cli_PathNotFound
    {
        get
        {
            return ResourceManager.GetString("Cli_PathNotFound", resourceCulture);
        }
    }

    internal static string Cli_HelpAbout
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpAbout", resourceCulture);
        }
    }

    internal static string Cli_HelpFormats
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpFormats", resourceCulture);
        }
    }

    internal static string Cli_HelpAccess
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpAccess", resourceCulture);
        }
    }

    internal static string Cli_HelpOut
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpOut", resourceCulture);
        }
    }

    internal static string Cli_HelpInPlace
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpInPlace", resourceCulture);
        }
    }

    internal static string Cli_HelpDryRun
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpDryRun", resourceCulture);
        }
    }

    internal static string Cli_HelpRecursive
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpRecursive", resourceCulture);
        }
    }

    internal static string Cli_HelpSignatures
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpSignatures", resourceCulture);
        }
    }

    internal static string Cli_HelpStrip
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpStrip", resourceCulture);
        }
    }

    internal static string Cli_HelpKeep
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpKeep", resourceCulture);
        }
    }

    internal static string Cli_HelpWait
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpWait", resourceCulture);
        }
    }

    internal static string Cli_HelpLang
    {
        get
        {
            return ResourceManager.GetString("Cli_HelpLang", resourceCulture);
        }
    }

    internal static string Cli_Usage
    {
        get
        {
            return ResourceManager.GetString("Cli_Usage", resourceCulture);
        }
    }

    internal static string Cli_WaitLocked
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitLocked", resourceCulture);
        }
    }

    internal static string Cli_WaitOfficeOpen
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitOfficeOpen", resourceCulture);
        }
    }

    internal static string Cli_WaitRunning
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitRunning", resourceCulture);
        }
    }

    internal static string Cli_WaitSkip
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitSkip", resourceCulture);
        }
    }

    internal static string Cli_WaitCancelled
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitCancelled", resourceCulture);
        }
    }

    internal static string Cli_WaitFreed
    {
        get
        {
            return ResourceManager.GetString("Cli_WaitFreed", resourceCulture);
        }
    }

    internal static string Cli_Error
    {
        get
        {
            return ResourceManager.GetString("Cli_Error", resourceCulture);
        }
    }

    internal static string Cli_Container
    {
        get
        {
            return ResourceManager.GetString("Cli_Container", resourceCulture);
        }
    }

    internal static string Cli_Dropped
    {
        get
        {
            return ResourceManager.GetString("Cli_Dropped", resourceCulture);
        }
    }

    internal static string Cli_Scrubbed
    {
        get
        {
            return ResourceManager.GetString("Cli_Scrubbed", resourceCulture);
        }
    }

    internal static string Cli_Operations
    {
        get
        {
            return ResourceManager.GetString("Cli_Operations", resourceCulture);
        }
    }

    internal static string Cli_NothingToClean
    {
        get
        {
            return ResourceManager.GetString("Cli_NothingToClean", resourceCulture);
        }
    }

    internal static string Cli_DryRunMode
    {
        get
        {
            return ResourceManager.GetString("Cli_DryRunMode", resourceCulture);
        }
    }

    internal static string Cli_Replaced
    {
        get
        {
            return ResourceManager.GetString("Cli_Replaced", resourceCulture);
        }
    }

    internal static string Cli_Written
    {
        get
        {
            return ResourceManager.GetString("Cli_Written", resourceCulture);
        }
    }

    internal static string Cli_NewSize
    {
        get
        {
            return ResourceManager.GetString("Cli_NewSize", resourceCulture);
        }
    }

    internal static string Cli_SizeBeforeAfter
    {
        get
        {
            return ResourceManager.GetString("Cli_SizeBeforeAfter", resourceCulture);
        }
    }

    internal static string Gui_Title
    {
        get
        {
            return ResourceManager.GetString("Gui_Title", resourceCulture);
        }
    }

    internal static string Gui_Subtitle
    {
        get
        {
            return ResourceManager.GetString("Gui_Subtitle", resourceCulture);
        }
    }

    internal static string Gui_SettingsTip
    {
        get
        {
            return ResourceManager.GetString("Gui_SettingsTip", resourceCulture);
        }
    }

    internal static string Gui_OptImages
    {
        get
        {
            return ResourceManager.GetString("Gui_OptImages", resourceCulture);
        }
    }

    internal static string Gui_HintImages
    {
        get
        {
            return ResourceManager.GetString("Gui_HintImages", resourceCulture);
        }
    }

    internal static string Gui_OptSignatures
    {
        get
        {
            return ResourceManager.GetString("Gui_OptSignatures", resourceCulture);
        }
    }

    internal static string Gui_HintSignatures
    {
        get
        {
            return ResourceManager.GetString("Gui_HintSignatures", resourceCulture);
        }
    }

    internal static string Gui_OptWait
    {
        get
        {
            return ResourceManager.GetString("Gui_OptWait", resourceCulture);
        }
    }

    internal static string Gui_HintWait
    {
        get
        {
            return ResourceManager.GetString("Gui_HintWait", resourceCulture);
        }
    }

    internal static string Gui_OptPrivacy
    {
        get
        {
            return ResourceManager.GetString("Gui_OptPrivacy", resourceCulture);
        }
    }

    internal static string Gui_HintPrivacy
    {
        get
        {
            return ResourceManager.GetString("Gui_HintPrivacy", resourceCulture);
        }
    }

    internal static string Gui_Language
    {
        get
        {
            return ResourceManager.GetString("Gui_Language", resourceCulture);
        }
    }

    internal static string Gui_LangSystem
    {
        get
        {
            return ResourceManager.GetString("Gui_LangSystem", resourceCulture);
        }
    }

    internal static string Gui_LangRestart
    {
        get
        {
            return ResourceManager.GetString("Gui_LangRestart", resourceCulture);
        }
    }

    internal static string Gui_ColFile
    {
        get
        {
            return ResourceManager.GetString("Gui_ColFile", resourceCulture);
        }
    }

    internal static string Gui_ColType
    {
        get
        {
            return ResourceManager.GetString("Gui_ColType", resourceCulture);
        }
    }

    internal static string Gui_ColStatus
    {
        get
        {
            return ResourceManager.GetString("Gui_ColStatus", resourceCulture);
        }
    }

    internal static string Gui_ColDetails
    {
        get
        {
            return ResourceManager.GetString("Gui_ColDetails", resourceCulture);
        }
    }

    internal static string Gui_EmptyHint
    {
        get
        {
            return ResourceManager.GetString("Gui_EmptyHint", resourceCulture);
        }
    }

    internal static string Gui_FilesSection
    {
        get
        {
            return ResourceManager.GetString("Gui_FilesSection", resourceCulture);
        }
    }

    internal static string Gui_InPlace
    {
        get
        {
            return ResourceManager.GetString("Gui_InPlace", resourceCulture);
        }
    }

    internal static string Gui_Beside
    {
        get
        {
            return ResourceManager.GetString("Gui_Beside", resourceCulture);
        }
    }

    internal static string Gui_ToFolder
    {
        get
        {
            return ResourceManager.GetString("Gui_ToFolder", resourceCulture);
        }
    }

    internal static string Gui_AddFiles
    {
        get
        {
            return ResourceManager.GetString("Gui_AddFiles", resourceCulture);
        }
    }

    internal static string Gui_AddFolder
    {
        get
        {
            return ResourceManager.GetString("Gui_AddFolder", resourceCulture);
        }
    }

    internal static string Gui_RemoveSelected
    {
        get
        {
            return ResourceManager.GetString("Gui_RemoveSelected", resourceCulture);
        }
    }

    internal static string Gui_ClearList
    {
        get
        {
            return ResourceManager.GetString("Gui_ClearList", resourceCulture);
        }
    }

    internal static string Gui_ResetMarks
    {
        get
        {
            return ResourceManager.GetString("Gui_ResetMarks", resourceCulture);
        }
    }

    internal static string Gui_OpenResult
    {
        get
        {
            return ResourceManager.GetString("Gui_OpenResult", resourceCulture);
        }
    }

    internal static string Gui_Cancel
    {
        get
        {
            return ResourceManager.GetString("Gui_Cancel", resourceCulture);
        }
    }

    internal static string Gui_Clean
    {
        get
        {
            return ResourceManager.GetString("Gui_Clean", resourceCulture);
        }
    }

    internal static string Gui_NoFiles
    {
        get
        {
            return ResourceManager.GetString("Gui_NoFiles", resourceCulture);
        }
    }

    internal static string Gui_SelectedN
    {
        get
        {
            return ResourceManager.GetString("Gui_SelectedN", resourceCulture);
        }
    }

    internal static string Gui_ProcessedOf
    {
        get
        {
            return ResourceManager.GetString("Gui_ProcessedOf", resourceCulture);
        }
    }

    internal static string Gui_DoneSummary
    {
        get
        {
            return ResourceManager.GetString("Gui_DoneSummary", resourceCulture);
        }
    }

    internal static string Gui_AlreadyDone
    {
        get
        {
            return ResourceManager.GetString("Gui_AlreadyDone", resourceCulture);
        }
    }

    internal static string Gui_AllDone
    {
        get
        {
            return ResourceManager.GetString("Gui_AllDone", resourceCulture);
        }
    }

    internal static string Gui_NeedFolder
    {
        get
        {
            return ResourceManager.GetString("Gui_NeedFolder", resourceCulture);
        }
    }

    internal static string Gui_NoOfficeFiles
    {
        get
        {
            return ResourceManager.GetString("Gui_NoOfficeFiles", resourceCulture);
        }
    }

    internal static string Gui_NotProcessed
    {
        get
        {
            return ResourceManager.GetString("Gui_NotProcessed", resourceCulture);
        }
    }

    internal static string Status_Pending
    {
        get
        {
            return ResourceManager.GetString("Status_Pending", resourceCulture);
        }
    }

    internal static string Status_Waiting
    {
        get
        {
            return ResourceManager.GetString("Status_Waiting", resourceCulture);
        }
    }

    internal static string Status_Processing
    {
        get
        {
            return ResourceManager.GetString("Status_Processing", resourceCulture);
        }
    }

    internal static string Status_Done
    {
        get
        {
            return ResourceManager.GetString("Status_Done", resourceCulture);
        }
    }

    internal static string Status_Skipped
    {
        get
        {
            return ResourceManager.GetString("Status_Skipped", resourceCulture);
        }
    }

    internal static string Status_Error
    {
        get
        {
            return ResourceManager.GetString("Status_Error", resourceCulture);
        }
    }

    internal static string Gui_WaitDetail
    {
        get
        {
            return ResourceManager.GetString("Gui_WaitDetail", resourceCulture);
        }
    }

    internal static string Gui_CancelledDetail
    {
        get
        {
            return ResourceManager.GetString("Gui_CancelledDetail", resourceCulture);
        }
    }

    internal static string Gui_PickFilesTitle
    {
        get
        {
            return ResourceManager.GetString("Gui_PickFilesTitle", resourceCulture);
        }
    }

    internal static string Gui_FilesFilter
    {
        get
        {
            return ResourceManager.GetString("Gui_FilesFilter", resourceCulture);
        }
    }

    internal static string Gui_AllFiles
    {
        get
        {
            return ResourceManager.GetString("Gui_AllFiles", resourceCulture);
        }
    }

    internal static string Gui_PickFolderTitle
    {
        get
        {
            return ResourceManager.GetString("Gui_PickFolderTitle", resourceCulture);
        }
    }

    internal static string Gui_SaveTitle
    {
        get
        {
            return ResourceManager.GetString("Gui_SaveTitle", resourceCulture);
        }
    }

    internal static string Gui_DetailsTitle
    {
        get
        {
            return ResourceManager.GetString("Gui_DetailsTitle", resourceCulture);
        }
    }

    internal static string Gui_DetailsFor
    {
        get
        {
            return ResourceManager.GetString("Gui_DetailsFor", resourceCulture);
        }
    }

    internal static string Gui_Close
    {
        get
        {
            return ResourceManager.GetString("Gui_Close", resourceCulture);
        }
    }

    internal static string Gui_DroppedParts
    {
        get
        {
            return ResourceManager.GetString("Gui_DroppedParts", resourceCulture);
        }
    }

    internal static string Gui_ScrubbedParts
    {
        get
        {
            return ResourceManager.GetString("Gui_ScrubbedParts", resourceCulture);
        }
    }

    internal static string Gui_OperationsDone
    {
        get
        {
            return ResourceManager.GetString("Gui_OperationsDone", resourceCulture);
        }
    }

    internal static string Gui_NothingToClean
    {
        get
        {
            return ResourceManager.GetString("Gui_NothingToClean", resourceCulture);
        }
    }

    internal static string Gui_DryRunTag
    {
        get
        {
            return ResourceManager.GetString("Gui_DryRunTag", resourceCulture);
        }
    }

    internal static string Gui_ReplacedTag
    {
        get
        {
            return ResourceManager.GetString("Gui_ReplacedTag", resourceCulture);
        }
    }
}
